
import type { UserProfile } from './types';

// Data is now mutable to simulate a database.
let allProfiles: UserProfile[] = [
  {
    id: '1',
    name: 'saytee.software',
    age: 49,
    email: 'saytee.software@gmail.com',
    location: 'London',
    interests: ['Art', 'Travel', 'Fine Dining'],
    wants: ['Mentorship', 'Discreet', 'Long-term'],
    bio: 'A student of art history with a passion for exploring new cultures. I enjoy gallery openings, weekend trips to Paris, and discovering hidden culinary gems.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    password: '12345',
    height: "5'11\"",
    bodyType: 'Athletic',
    hairColor: 'Brown',
    eyeColor: 'Hazel',
    piercings: 'None',
    tattoos: 'Hidden',
    smokes: 'No',
    drinks: 'Socially',
    education: "Master's Degree",
  },
  {
    id: '2',
    name: 'Oliver',
    age: 35,
    email: 'oliver@example.com',
    location: 'Manchester',
    interests: ['Business', 'Fitness', 'Watches'],
    wants: ['Networking', 'Ambitious Partner', 'No Drama'],
    bio: 'Entrepreneur with a focus on tech startups. When I\'m not working, I\'m in the gym or planning my next investment. Looking for an intelligent and ambitious partner.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    height: "6'1\"",
    bodyType: 'Athletic',
    hairColor: 'Blonde',
    eyeColor: 'Blue',
    piercings: 'None',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'Socially',
    education: "Bachelor's Degree",
  },
  {
    id: '3',
    name: 'Isabella',
    age: 28,
    email: 'isabella@example.com',
    location: 'Edinburgh',
    interests: ['Literature', 'Horses', 'Charity'],
    wants: ['Respectful', 'Good Conversation', 'Generous Spirit'],
    bio: 'I split my time between managing a family charity foundation and my passion for equestrian sports. A good book and a quiet evening are my idea of heaven.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: false,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'Mixed / Multiple ethnic groups',
    height: "5'6\"",
    bodyType: 'Slim',
    hairColor: 'Dark Brown',
    eyeColor: 'Green',
    piercings: 'Ears',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'Socially',
    education: "Master's Degree",
  },
  {
    id: '4',
    name: 'George',
    age: 42,
    email: 'george@example.com',
    location: 'Bristol',
    interests: ['Sailing', 'Architecture', 'Jazz'],
    wants: ['Companionship', 'Shared Adventures', 'Easy Going'],
    bio: 'Architect with a love for the sea. I spend my weekends sailing along the coast. Searching for a companion to share adventures and quiet moments with.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    height: "5'10\"",
    bodyType: 'Average',
    hairColor: 'Salt and Pepper',
    eyeColor: 'Brown',
    piercings: 'None',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'Socially',
    education: "Bachelor's Degree",
  },
  {
    id: '5',
    name: 'Sophia',
    age: 22,
    email: 'sophia@example.com',
    location: 'Birmingham',
    interests: ['Fashion', 'Social Media', 'Dancing'],
    wants: ['Spoiling', 'Luxury Lifestyle', 'Travel'],
    bio: 'Fashion blogger and social media influencer. My life is fast-paced and exciting. Looking for someone who can keep up and enjoys the finer things.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'Asian / Asian British',
    height: "5'4\"",
    bodyType: 'Slim',
    hairColor: 'Black',
    eyeColor: 'Brown',
    piercings: 'Other',
    tattoos: 'One',
    smokes: 'No',
    drinks: 'Socially',
    education: 'Some College',
  },
  {
    id: '6',
    name: 'Harry',
    age: 31,
    email: 'harry@example.com',
    location: 'London',
    interests: ['Finance', 'Golf', 'Cars'],
    wants: ['Fun', 'Excitement', 'Discretion'],
    bio: 'Investment banker in the city. Work hard, play hard is my motto. I enjoy weekends on the golf course and driving my sports car.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: false,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    height: "6'0\"",
    bodyType: 'Athletic',
    hairColor: 'Brown',
    eyeColor: 'Brown',
    piercings: 'None',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'Socially',
    education: "MBA",
  },
  {
    id: '7',
    name: 'Charlotte',
    age: 29,
    email: 'charlotte@example.com',
    location: 'Leeds',
    interests: ['Yoga', 'Vegan cooking', 'Music'],
    wants: ['Intellectual Connection', 'Mutual Respect', 'Supportive'],
    bio: 'Lawyer by day, yoga enthusiast by night. I believe in a balanced life of professional ambition and personal wellness. Seeking a genuine connection.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    height: "5'8\"",
    bodyType: 'Athletic',
    hairColor: 'Blonde',
    eyeColor: 'Blue',
    piercings: 'Ears',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'No',
    education: 'Juris Doctor',
  },
  {
    id: '8',
    name: 'Arthur',
    age: 50,
    email: 'arthur@example.com',
    location: 'Cornwall',
    interests: ['Wine', 'History', 'Gardening'],
    wants: ['Kindness', 'Grace', 'Shared quiet moments'],
    bio: 'Retired surgeon, now a vineyard owner in Cornwall. Life is slower now, and I appreciate the simple pleasures. Looking for a graceful and kind partner.',
    profileImage: 'https://placehold.co/600x400.png',
    isVerified: true,
    gallery: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    ethnicity: 'White',
    height: "5'9\"",
    bodyType: 'Average',
    hairColor: 'Grey',
    eyeColor: 'Green',
    piercings: 'None',
    tattoos: 'None',
    smokes: 'No',
    drinks: 'Daily',
    education: 'MD',
  },
];

let conversations = [
    {
      id: 'conv1',
      userId: '2',
      userName: 'Oliver',
      lastMessage: 'I\'m intrigued by your profile. Tell me more about your work.',
      avatar: 'https://placehold.co/600x400.png',
      unreadCount: 2,
    },
    {
      id: 'conv2',
      userId: '4',
      userName: 'George',
      lastMessage: 'I saw you enjoy sailing. We should connect.',
      avatar: 'https://placehold.co/600x400.png',
      unreadCount: 0,
    },
     {
      id: 'conv3',
      userId: '8',
      userName: 'Arthur',
      lastMessage: 'A vineyard sounds lovely. I\'ve always wanted to visit Cornwall.',
      avatar: 'https://placehold.co/600x400.png',
      unreadCount: 0,
    },
];

let messages = {
    conv1: [
        { id: 'msg1', sender: 'Oliver', text: 'Hello, I came across your profile and was very impressed.' },
        { id: 'msg2', sender: 'Me', text: 'Hi Oliver, thank you! Your profile is quite impressive as well.' },
        { id: 'msg3', sender: 'Oliver', text: 'I\'m intrigued by your profile. Tell me more about your work.' },
    ],
    conv2: [
        { id: 'msg1', sender: 'George', text: 'I saw you enjoy sailing. We should connect.' },
    ],
     conv3: [
        { id: 'msg1', sender: 'Arthur', text: 'A vineyard sounds lovely. I\'ve always wanted to visit Cornwall.' },
    ],
};

let favorites = ['2', '5', '7'];
let visitors = ['4', '6'];
let viewed = ['3', '8'];


// Simulate a database
export const db = {
  getProfiles: async () => allProfiles,
  getFeaturedProfiles: async () => allProfiles.slice(0, 4),
  getProfileById: async (id: string) => allProfiles.find(p => p.id === id),
  getProfileByName: async (name: string) => allProfiles.find(p => p.name === name),
  updateProfile: async (id: string, data: Partial<UserProfile>) => {
    const profileIndex = allProfiles.findIndex(p => p.id === id);
    if (profileIndex > -1) {
      allProfiles[profileIndex] = { ...allProfiles[profileIndex], ...data };
      return allProfiles[profileIndex];
    }
    return null;
  },
  getConversations: async () => conversations.map(c => ({...c, avatar: allProfiles.find(p => p.id === c.userId)?.profileImage || c.avatar})),
  getMessages: async () => messages,
  getLocations: async () => [...new Set(allProfiles.map(p => p.location))],
  getAllInterests: async () => [...new Set(allProfiles.flatMap(p => p.interests))],
  getFavorites: async () => allProfiles.filter(p => favorites.includes(p.id)),
  getVisitors: async () => allProfiles.filter(p => visitors.includes(p.id)),
  getViewed: async () => allProfiles.filter(p => viewed.includes(p.id)),
};
