
[build]
  command = "npm run build"
  publish = ".next"

[blobs]
  # Enable the blobs feature
  store = "data"

[[redirects]]
  from = "/api/uploads/*"
  to = "/.netlify/functions/server/api/uploads/:splat"
  status = 200
  force = true
